// Mocks generated by Mockito 5.4.6 from annotations
// in jot_app/test/unit/mock_generator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i11;

import 'package:jot_app/models/auth_state.dart' as _i13;
import 'package:jot_app/models/note_model.dart' as _i3;
import 'package:jot_app/models/sync_result.dart' as _i2;
import 'package:jot_app/models/sync_state.dart' as _i9;
import 'package:jot_app/models/todo_model.dart' as _i7;
import 'package:jot_app/services/i_auth_service.dart' as _i4;
import 'package:jot_app/services/i_local_storage_service.dart' as _i5;
import 'package:jot_app/services/i_note_service.dart' as _i14;
import 'package:jot_app/services/i_remote_storage_service.dart' as _i10;
import 'package:jot_app/services/i_sync_engine.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNote_1 extends _i1.SmartFake implements _i3.Note {
  _FakeNote_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResult_2 extends _i1.SmartFake implements _i4.AuthResult {
  _FakeAuthResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ILocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocalStorageService extends _i1.Mock
    implements _i5.ILocalStorageService {
  MockILocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> insertNote(_i3.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #insertNote,
          [note],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.Note?> getNoteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getNoteById,
          [id],
        ),
        returnValue: _i6.Future<_i3.Note?>.value(),
      ) as _i6.Future<_i3.Note?>);

  @override
  _i6.Future<List<_i3.Note>> getAllNotes(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getAllNotes,
          [userId],
        ),
        returnValue: _i6.Future<List<_i3.Note>>.value(<_i3.Note>[]),
      ) as _i6.Future<List<_i3.Note>>);

  @override
  _i6.Future<List<_i3.Note>> getAllNotesForSync(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllNotesForSync,
          [userId],
        ),
        returnValue: _i6.Future<List<_i3.Note>>.value(<_i3.Note>[]),
      ) as _i6.Future<List<_i3.Note>>);

  @override
  _i6.Future<void> updateNote(_i3.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [note],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> softDeleteNote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #softDeleteNote,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> hardDeleteNote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #hardDeleteNote,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.Note>> getNotesModifiedAfter(
    DateTime? timestamp,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotesModifiedAfter,
          [
            timestamp,
            userId,
          ],
        ),
        returnValue: _i6.Future<List<_i3.Note>>.value(<_i3.Note>[]),
      ) as _i6.Future<List<_i3.Note>>);

  @override
  _i6.Future<void> clearAllNotes([String? userId]) => (super.noSuchMethod(
        Invocation.method(
          #clearAllNotes,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> insertTodoList(_i7.TodoList? todoList) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTodoList,
          [todoList],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateTodoList(_i7.TodoList? todoList) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTodoList,
          [todoList],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteTodoList(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodoList,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.TodoList>> getTodoListsForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodoListsForUser,
          [userId],
        ),
        returnValue: _i6.Future<List<_i7.TodoList>>.value(<_i7.TodoList>[]),
      ) as _i6.Future<List<_i7.TodoList>>);
}

/// A class which mocks [ISyncEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockISyncEngine extends _i1.Mock implements _i8.ISyncEngine {
  MockISyncEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i9.SyncState> get syncStatus => (super.noSuchMethod(
        Invocation.getter(#syncStatus),
        returnValue: _i6.Stream<_i9.SyncState>.empty(),
      ) as _i6.Stream<_i9.SyncState>);

  @override
  bool get isSyncing => (super.noSuchMethod(
        Invocation.getter(#isSyncing),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> start(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #start,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.SyncResult> syncNow(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #syncNow,
          [userId],
        ),
        returnValue: _i6.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncNow,
            [userId],
          ),
        )),
      ) as _i6.Future<_i2.SyncResult>);

  @override
  _i6.Future<void> pushLocalChanges(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #pushLocalChanges,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> pullCloudChanges(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #pullCloudChanges,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IRemoteStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRemoteStorageService extends _i1.Mock
    implements _i10.IRemoteStorageService {
  MockIRemoteStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Note> uploadNote(_i3.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #uploadNote,
          [note],
        ),
        returnValue: _i6.Future<_i3.Note>.value(_FakeNote_1(
          this,
          Invocation.method(
            #uploadNote,
            [note],
          ),
        )),
      ) as _i6.Future<_i3.Note>);

  @override
  _i6.Future<_i3.Note?> downloadNote(
    String? userId,
    String? noteId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadNote,
          [
            userId,
            noteId,
          ],
        ),
        returnValue: _i6.Future<_i3.Note?>.value(),
      ) as _i6.Future<_i3.Note?>);

  @override
  _i6.Future<List<_i3.Note>> downloadAllNotes(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadAllNotes,
          [userId],
        ),
        returnValue: _i6.Future<List<_i3.Note>>.value(<_i3.Note>[]),
      ) as _i6.Future<List<_i3.Note>>);

  @override
  _i6.Future<void> deleteNote(
    String? userId,
    String? noteId, {
    String? remoteId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [
            userId,
            noteId,
          ],
          {#remoteId: remoteId},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i3.Note>> watchNotes(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #watchNotes,
          [userId],
        ),
        returnValue: _i6.Stream<List<_i3.Note>>.empty(),
      ) as _i6.Stream<List<_i3.Note>>);

  @override
  _i6.Future<void> batchUploadNotes(List<_i3.Note>? notes) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUploadNotes,
          [notes],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String> uploadImage(
    _i11.Uint8List? bytes,
    String? filename,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [
            bytes,
            filename,
          ],
        ),
        returnValue: _i6.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImage,
            [
              bytes,
              filename,
            ],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<String> getImageUrl(String? fileId) => (super.noSuchMethod(
        Invocation.method(
          #getImageUrl,
          [fileId],
        ),
        returnValue: _i6.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getImageUrl,
            [fileId],
          ),
        )),
      ) as _i6.Future<String>);
}

/// A class which mocks [IAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthService extends _i1.Mock implements _i4.IAuthService {
  MockIAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i13.AuthState> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i6.Stream<_i13.AuthState>.empty(),
      ) as _i6.Stream<_i13.AuthState>);

  @override
  _i6.Future<_i4.AuthResult> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i6.Future<_i4.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #signInWithEmail,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i6.Future<_i4.AuthResult>);

  @override
  _i6.Future<_i4.AuthResult> signUpWithEmail(
    String? email,
    String? password, {
    String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmail,
          [
            email,
            password,
          ],
          {#displayName: displayName},
        ),
        returnValue: _i6.Future<_i4.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #signUpWithEmail,
            [
              email,
              password,
            ],
            {#displayName: displayName},
          ),
        )),
      ) as _i6.Future<_i4.AuthResult>);

  @override
  _i6.Future<_i4.AuthResult> signInWithGmail() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGmail,
          [],
        ),
        returnValue: _i6.Future<_i4.AuthResult>.value(_FakeAuthResult_2(
          this,
          Invocation.method(
            #signInWithGmail,
            [],
          ),
        )),
      ) as _i6.Future<_i4.AuthResult>);

  @override
  _i6.Future<bool> restoreSession() => (super.noSuchMethod(
        Invocation.method(
          #restoreSession,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  bool isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [INoteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockINoteService extends _i1.Mock implements _i14.INoteService {
  MockINoteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Note> createNote({
    required String? userId,
    required String? title,
    required String? content,
    _i3.NoteType? type = _i3.NoteType.text,
    List<String>? imageIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNote,
          [],
          {
            #userId: userId,
            #title: title,
            #content: content,
            #type: type,
            #imageIds: imageIds,
          },
        ),
        returnValue: _i6.Future<_i3.Note>.value(_FakeNote_1(
          this,
          Invocation.method(
            #createNote,
            [],
            {
              #userId: userId,
              #title: title,
              #content: content,
              #type: type,
              #imageIds: imageIds,
            },
          ),
        )),
      ) as _i6.Future<_i3.Note>);

  @override
  _i6.Future<_i3.Note?> getNote(String? noteId) => (super.noSuchMethod(
        Invocation.method(
          #getNote,
          [noteId],
        ),
        returnValue: _i6.Future<_i3.Note?>.value(),
      ) as _i6.Future<_i3.Note?>);

  @override
  _i6.Future<List<_i3.Note>> getAllNotes(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getAllNotes,
          [userId],
        ),
        returnValue: _i6.Future<List<_i3.Note>>.value(<_i3.Note>[]),
      ) as _i6.Future<List<_i3.Note>>);

  @override
  _i6.Future<_i3.Note> updateNote(
    _i3.Note? note, {
    String? title,
    String? content,
    _i3.NoteType? type,
    List<String>? imageIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [note],
          {
            #title: title,
            #content: content,
            #type: type,
            #imageIds: imageIds,
          },
        ),
        returnValue: _i6.Future<_i3.Note>.value(_FakeNote_1(
          this,
          Invocation.method(
            #updateNote,
            [note],
            {
              #title: title,
              #content: content,
              #type: type,
              #imageIds: imageIds,
            },
          ),
        )),
      ) as _i6.Future<_i3.Note>);

  @override
  _i6.Future<void> deleteNote(_i3.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [note],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i3.Note>> watchNotes(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #watchNotes,
          [userId],
        ),
        returnValue: _i6.Stream<List<_i3.Note>>.empty(),
      ) as _i6.Stream<List<_i3.Note>>);

  @override
  _i6.Future<List<_i3.Note>> searchNotes(
    String? userId,
    String? query, {
    String? tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchNotes,
          [
            userId,
            query,
          ],
          {#tag: tag},
        ),
        returnValue: _i6.Future<List<_i3.Note>>.value(<_i3.Note>[]),
      ) as _i6.Future<List<_i3.Note>>);
}
