// Mocks generated by Mockito 5.4.6 from annotations
// in jot_app/test/unit/note_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jot_app/models/note_model.dart' as _i5;
import 'package:jot_app/models/sync_result.dart' as _i2;
import 'package:jot_app/models/sync_state.dart' as _i8;
import 'package:jot_app/models/todo_model.dart' as _i6;
import 'package:jot_app/services/i_local_storage_service.dart' as _i3;
import 'package:jot_app/services/i_sync_engine.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ILocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocalStorageService extends _i1.Mock
    implements _i3.ILocalStorageService {
  MockILocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertNote(_i5.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #insertNote,
          [note],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.Note?> getNoteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getNoteById,
          [id],
        ),
        returnValue: _i4.Future<_i5.Note?>.value(),
      ) as _i4.Future<_i5.Note?>);

  @override
  _i4.Future<List<_i5.Note>> getAllNotes(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getAllNotes,
          [userId],
        ),
        returnValue: _i4.Future<List<_i5.Note>>.value(<_i5.Note>[]),
      ) as _i4.Future<List<_i5.Note>>);

  @override
  _i4.Future<List<_i5.Note>> getAllNotesForSync(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllNotesForSync,
          [userId],
        ),
        returnValue: _i4.Future<List<_i5.Note>>.value(<_i5.Note>[]),
      ) as _i4.Future<List<_i5.Note>>);

  @override
  _i4.Future<void> updateNote(_i5.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [note],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> softDeleteNote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #softDeleteNote,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> hardDeleteNote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #hardDeleteNote,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Note>> getNotesModifiedAfter(
    DateTime? timestamp,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotesModifiedAfter,
          [
            timestamp,
            userId,
          ],
        ),
        returnValue: _i4.Future<List<_i5.Note>>.value(<_i5.Note>[]),
      ) as _i4.Future<List<_i5.Note>>);

  @override
  _i4.Future<void> clearAllNotes([String? userId]) => (super.noSuchMethod(
        Invocation.method(
          #clearAllNotes,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertTodoList(_i6.TodoList? todoList) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTodoList,
          [todoList],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTodoList(_i6.TodoList? todoList) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTodoList,
          [todoList],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTodoList(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodoList,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.TodoList>> getTodoListsForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodoListsForUser,
          [userId],
        ),
        returnValue: _i4.Future<List<_i6.TodoList>>.value(<_i6.TodoList>[]),
      ) as _i4.Future<List<_i6.TodoList>>);
}

/// A class which mocks [ISyncEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockISyncEngine extends _i1.Mock implements _i7.ISyncEngine {
  MockISyncEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i8.SyncState> get syncStatus => (super.noSuchMethod(
        Invocation.getter(#syncStatus),
        returnValue: _i4.Stream<_i8.SyncState>.empty(),
      ) as _i4.Stream<_i8.SyncState>);

  @override
  bool get isSyncing => (super.noSuchMethod(
        Invocation.getter(#isSyncing),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> start(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #start,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.SyncResult> syncNow(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #syncNow,
          [userId],
        ),
        returnValue: _i4.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncNow,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.SyncResult>);

  @override
  _i4.Future<void> pushLocalChanges(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #pushLocalChanges,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> pullCloudChanges(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #pullCloudChanges,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
