// Mocks generated by Mockito 5.4.6 from annotations
// in jot_app/test/integration/sync_engine_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i7;

import 'package:jot_app/models/note_model.dart' as _i2;
import 'package:jot_app/models/todo_model.dart' as _i5;
import 'package:jot_app/services/i_local_storage_service.dart' as _i3;
import 'package:jot_app/services/i_remote_storage_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNote_0 extends _i1.SmartFake implements _i2.Note {
  _FakeNote_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ILocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocalStorageService extends _i1.Mock
    implements _i3.ILocalStorageService {
  MockILocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertNote(_i2.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #insertNote,
          [note],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Note?> getNoteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getNoteById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Note?>.value(),
      ) as _i4.Future<_i2.Note?>);

  @override
  _i4.Future<List<_i2.Note>> getAllNotes(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getAllNotes,
          [userId],
        ),
        returnValue: _i4.Future<List<_i2.Note>>.value(<_i2.Note>[]),
      ) as _i4.Future<List<_i2.Note>>);

  @override
  _i4.Future<List<_i2.Note>> getAllNotesForSync(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllNotesForSync,
          [userId],
        ),
        returnValue: _i4.Future<List<_i2.Note>>.value(<_i2.Note>[]),
      ) as _i4.Future<List<_i2.Note>>);

  @override
  _i4.Future<void> updateNote(_i2.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [note],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> softDeleteNote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #softDeleteNote,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> hardDeleteNote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #hardDeleteNote,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Note>> getNotesModifiedAfter(
    DateTime? timestamp,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotesModifiedAfter,
          [
            timestamp,
            userId,
          ],
        ),
        returnValue: _i4.Future<List<_i2.Note>>.value(<_i2.Note>[]),
      ) as _i4.Future<List<_i2.Note>>);

  @override
  _i4.Future<void> clearAllNotes([String? userId]) => (super.noSuchMethod(
        Invocation.method(
          #clearAllNotes,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertTodoList(_i5.TodoList? todoList) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTodoList,
          [todoList],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTodoList(_i5.TodoList? todoList) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTodoList,
          [todoList],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTodoList(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodoList,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.TodoList>> getTodoListsForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodoListsForUser,
          [userId],
        ),
        returnValue: _i4.Future<List<_i5.TodoList>>.value(<_i5.TodoList>[]),
      ) as _i4.Future<List<_i5.TodoList>>);
}

/// A class which mocks [IRemoteStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRemoteStorageService extends _i1.Mock
    implements _i6.IRemoteStorageService {
  MockIRemoteStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Note> uploadNote(_i2.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #uploadNote,
          [note],
        ),
        returnValue: _i4.Future<_i2.Note>.value(_FakeNote_0(
          this,
          Invocation.method(
            #uploadNote,
            [note],
          ),
        )),
      ) as _i4.Future<_i2.Note>);

  @override
  _i4.Future<_i2.Note?> downloadNote(
    String? userId,
    String? noteId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadNote,
          [
            userId,
            noteId,
          ],
        ),
        returnValue: _i4.Future<_i2.Note?>.value(),
      ) as _i4.Future<_i2.Note?>);

  @override
  _i4.Future<List<_i2.Note>> downloadAllNotes(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadAllNotes,
          [userId],
        ),
        returnValue: _i4.Future<List<_i2.Note>>.value(<_i2.Note>[]),
      ) as _i4.Future<List<_i2.Note>>);

  @override
  _i4.Future<void> deleteNote(
    String? userId,
    String? noteId, {
    String? remoteId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [
            userId,
            noteId,
          ],
          {#remoteId: remoteId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i2.Note>> watchNotes(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #watchNotes,
          [userId],
        ),
        returnValue: _i4.Stream<List<_i2.Note>>.empty(),
      ) as _i4.Stream<List<_i2.Note>>);

  @override
  _i4.Future<void> batchUploadNotes(List<_i2.Note>? notes) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUploadNotes,
          [notes],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> uploadImage(
    _i7.Uint8List? bytes,
    String? filename,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [
            bytes,
            filename,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #uploadImage,
            [
              bytes,
              filename,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> getImageUrl(String? fileId) => (super.noSuchMethod(
        Invocation.method(
          #getImageUrl,
          [fileId],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getImageUrl,
            [fileId],
          ),
        )),
      ) as _i4.Future<String>);
}
